---
hero_image: images/banner.png
theme: red
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Flappy Parrot
description: 
original_url: https://codeclubprojects.org/en-GB/scratch/flappy-parrot
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Make Flappy fall
- title: Make Flappy fly
- title: Fix the controls
- title: Add the pipes
- title: Make the pipes move
- title: Detect collision with the pipes
- title: Add scoring

