title: Flappy Parrot
hero_image: images/banner.png
description: Create a game in the style of the popular mobile game Flappy Bird.
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
listed: false
ingredient: false
duration: 2
interests: "games, graphics, animals"
technology: "scratch"
steps:
  - title: "Introduction"
  - title: "What you will need"
  - title: "Add the pipes"
  - title: "Make the pipes move"
  - title: "Make Flappy fall"
  - title: "Make Flappy fly"
  - title: "Detect collision with the pipes"
  - title: "Add scoring"
  - title: "Challenge: adjust the difficulty"
  - title: "Challenge: add a high score"
